# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wenet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/wenet.proto',
  package='wenet',
  syntax='proto3',
  serialized_options=b'\n\007ex.grpc\242\002\005wenet',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11proto/wenet.proto\x12\x05wenet\"\xb1\x01\n\x07Request\x12\x34\n\rdecode_config\x18\x01 \x01(\x0b\x32\x1b.wenet.Request.DecodeConfigH\x00\x12\x14\n\naudio_data\x18\x02 \x01(\x0cH\x00\x1aH\n\x0c\x44\x65\x63odeConfig\x12\x14\n\x0cnbest_config\x18\x01 \x01(\x05\x12\"\n\x1a\x63ontinuous_decoding_config\x18\x02 \x01(\x08\x42\x10\n\x0eRequestPayload\"\xed\x02\n\x08Response\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.wenet.Response.Status\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.wenet.Response.Type\x12&\n\x05nbest\x18\x03 \x03(\x0b\x32\x17.wenet.Response.OneBest\x1aI\n\x07OneBest\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12,\n\nwordpieces\x18\x02 \x03(\x0b\x32\x18.wenet.Response.OnePiece\x1a\x34\n\x08OnePiece\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\"\x1c\n\x06Status\x12\x06\n\x02ok\x10\x00\x12\n\n\x06\x66\x61iled\x10\x01\"N\n\x04Type\x12\x10\n\x0cserver_ready\x10\x00\x12\x12\n\x0epartial_result\x10\x01\x12\x10\n\x0c\x66inal_result\x10\x02\x12\x0e\n\nspeech_end\x10\x03\x32\x39\n\x03\x41SR\x12\x32\n\tRecognize\x12\x0e.wenet.Request\x1a\x0f.wenet.Response\"\x00(\x01\x30\x01\x42\x11\n\x07\x65x.grpc\xa2\x02\x05wenetb\x06proto3'
)



_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='wenet.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ok', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='failed', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=466,
  serialized_end=494,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)

_RESPONSE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='wenet.Response.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='server_ready', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='partial_result', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='final_result', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='speech_end', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=496,
  serialized_end=574,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_TYPE)


_REQUEST_DECODECONFIG = _descriptor.Descriptor(
  name='DecodeConfig',
  full_name='wenet.Request.DecodeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nbest_config', full_name='wenet.Request.DecodeConfig.nbest_config', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='continuous_decoding_config', full_name='wenet.Request.DecodeConfig.continuous_decoding_config', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=188,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='wenet.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='decode_config', full_name='wenet.Request.decode_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_data', full_name='wenet.Request.audio_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_DECODECONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='RequestPayload', full_name='wenet.Request.RequestPayload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=206,
)


_RESPONSE_ONEBEST = _descriptor.Descriptor(
  name='OneBest',
  full_name='wenet.Response.OneBest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='wenet.Response.OneBest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wordpieces', full_name='wenet.Response.OneBest.wordpieces', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=410,
)

_RESPONSE_ONEPIECE = _descriptor.Descriptor(
  name='OnePiece',
  full_name='wenet.Response.OnePiece',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='wenet.Response.OnePiece.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='wenet.Response.OnePiece.start', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='wenet.Response.OnePiece.end', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=464,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='wenet.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='wenet.Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='wenet.Response.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nbest', full_name='wenet.Response.nbest', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_ONEBEST, _RESPONSE_ONEPIECE, ],
  enum_types=[
    _RESPONSE_STATUS,
    _RESPONSE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=574,
)

_REQUEST_DECODECONFIG.containing_type = _REQUEST
_REQUEST.fields_by_name['decode_config'].message_type = _REQUEST_DECODECONFIG
_REQUEST.oneofs_by_name['RequestPayload'].fields.append(
  _REQUEST.fields_by_name['decode_config'])
_REQUEST.fields_by_name['decode_config'].containing_oneof = _REQUEST.oneofs_by_name['RequestPayload']
_REQUEST.oneofs_by_name['RequestPayload'].fields.append(
  _REQUEST.fields_by_name['audio_data'])
_REQUEST.fields_by_name['audio_data'].containing_oneof = _REQUEST.oneofs_by_name['RequestPayload']
_RESPONSE_ONEBEST.fields_by_name['wordpieces'].message_type = _RESPONSE_ONEPIECE
_RESPONSE_ONEBEST.containing_type = _RESPONSE
_RESPONSE_ONEPIECE.containing_type = _RESPONSE
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE.fields_by_name['type'].enum_type = _RESPONSE_TYPE
_RESPONSE.fields_by_name['nbest'].message_type = _RESPONSE_ONEBEST
_RESPONSE_STATUS.containing_type = _RESPONSE
_RESPONSE_TYPE.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'DecodeConfig' : _reflection.GeneratedProtocolMessageType('DecodeConfig', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_DECODECONFIG,
    '__module__' : 'proto.wenet_pb2'
    # @@protoc_insertion_point(class_scope:wenet.Request.DecodeConfig)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'proto.wenet_pb2'
  # @@protoc_insertion_point(class_scope:wenet.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.DecodeConfig)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {

  'OneBest' : _reflection.GeneratedProtocolMessageType('OneBest', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_ONEBEST,
    '__module__' : 'proto.wenet_pb2'
    # @@protoc_insertion_point(class_scope:wenet.Response.OneBest)
    })
  ,

  'OnePiece' : _reflection.GeneratedProtocolMessageType('OnePiece', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_ONEPIECE,
    '__module__' : 'proto.wenet_pb2'
    # @@protoc_insertion_point(class_scope:wenet.Response.OnePiece)
    })
  ,
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'proto.wenet_pb2'
  # @@protoc_insertion_point(class_scope:wenet.Response)
  })
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.OneBest)
_sym_db.RegisterMessage(Response.OnePiece)


DESCRIPTOR._options = None

_ASR = _descriptor.ServiceDescriptor(
  name='ASR',
  full_name='wenet.ASR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=576,
  serialized_end=633,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recognize',
    full_name='wenet.ASR.Recognize',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASR)

DESCRIPTOR.services_by_name['ASR'] = _ASR

# @@protoc_insertion_point(module_scope)
