// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/wenet.proto

package ex.grpc;

public final class Wenet {
  private Wenet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wenet.Request)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
     * @return Whether the decodeConfig field is set.
     */
    boolean hasDecodeConfig();
    /**
     * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
     * @return The decodeConfig.
     */
    ex.grpc.Wenet.Request.DecodeConfig getDecodeConfig();

    /**
     * <code>bytes audio_data = 2;</code>
     * @return Whether the audioData field is set.
     */
    boolean hasAudioData();
    /**
     * <code>bytes audio_data = 2;</code>
     * @return The audioData.
     */
    com.google.protobuf.ByteString getAudioData();

    public ex.grpc.Wenet.Request.RequestPayloadCase getRequestPayloadCase();
  }
  /**
   * Protobuf type {@code wenet.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageLite<
          Request, Request.Builder> implements
      // @@protoc_insertion_point(message_implements:wenet.Request)
      RequestOrBuilder {
    private Request() {
    }
    public interface DecodeConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:wenet.Request.DecodeConfig)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>int32 nbest_config = 1;</code>
       * @return The nbestConfig.
       */
      int getNbestConfig();

      /**
       * <code>bool continuous_decoding_config = 2;</code>
       * @return The continuousDecodingConfig.
       */
      boolean getContinuousDecodingConfig();
    }
    /**
     * Protobuf type {@code wenet.Request.DecodeConfig}
     */
    public  static final class DecodeConfig extends
        com.google.protobuf.GeneratedMessageLite<
            DecodeConfig, DecodeConfig.Builder> implements
        // @@protoc_insertion_point(message_implements:wenet.Request.DecodeConfig)
        DecodeConfigOrBuilder {
      private DecodeConfig() {
      }
      public static final int NBEST_CONFIG_FIELD_NUMBER = 1;
      private int nbestConfig_;
      /**
       * <code>int32 nbest_config = 1;</code>
       * @return The nbestConfig.
       */
      @java.lang.Override
      public int getNbestConfig() {
        return nbestConfig_;
      }
      /**
       * <code>int32 nbest_config = 1;</code>
       * @param value The nbestConfig to set.
       */
      private void setNbestConfig(int value) {
        
        nbestConfig_ = value;
      }
      /**
       * <code>int32 nbest_config = 1;</code>
       */
      private void clearNbestConfig() {
        
        nbestConfig_ = 0;
      }

      public static final int CONTINUOUS_DECODING_CONFIG_FIELD_NUMBER = 2;
      private boolean continuousDecodingConfig_;
      /**
       * <code>bool continuous_decoding_config = 2;</code>
       * @return The continuousDecodingConfig.
       */
      @java.lang.Override
      public boolean getContinuousDecodingConfig() {
        return continuousDecodingConfig_;
      }
      /**
       * <code>bool continuous_decoding_config = 2;</code>
       * @param value The continuousDecodingConfig to set.
       */
      private void setContinuousDecodingConfig(boolean value) {
        
        continuousDecodingConfig_ = value;
      }
      /**
       * <code>bool continuous_decoding_config = 2;</code>
       */
      private void clearContinuousDecodingConfig() {
        
        continuousDecodingConfig_ = false;
      }

      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Request.DecodeConfig parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(ex.grpc.Wenet.Request.DecodeConfig prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code wenet.Request.DecodeConfig}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            ex.grpc.Wenet.Request.DecodeConfig, Builder> implements
          // @@protoc_insertion_point(builder_implements:wenet.Request.DecodeConfig)
          ex.grpc.Wenet.Request.DecodeConfigOrBuilder {
        // Construct using ex.grpc.Wenet.Request.DecodeConfig.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>int32 nbest_config = 1;</code>
         * @return The nbestConfig.
         */
        @java.lang.Override
        public int getNbestConfig() {
          return instance.getNbestConfig();
        }
        /**
         * <code>int32 nbest_config = 1;</code>
         * @param value The nbestConfig to set.
         * @return This builder for chaining.
         */
        public Builder setNbestConfig(int value) {
          copyOnWrite();
          instance.setNbestConfig(value);
          return this;
        }
        /**
         * <code>int32 nbest_config = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNbestConfig() {
          copyOnWrite();
          instance.clearNbestConfig();
          return this;
        }

        /**
         * <code>bool continuous_decoding_config = 2;</code>
         * @return The continuousDecodingConfig.
         */
        @java.lang.Override
        public boolean getContinuousDecodingConfig() {
          return instance.getContinuousDecodingConfig();
        }
        /**
         * <code>bool continuous_decoding_config = 2;</code>
         * @param value The continuousDecodingConfig to set.
         * @return This builder for chaining.
         */
        public Builder setContinuousDecodingConfig(boolean value) {
          copyOnWrite();
          instance.setContinuousDecodingConfig(value);
          return this;
        }
        /**
         * <code>bool continuous_decoding_config = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearContinuousDecodingConfig() {
          copyOnWrite();
          instance.clearContinuousDecodingConfig();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:wenet.Request.DecodeConfig)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new ex.grpc.Wenet.Request.DecodeConfig();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "nbestConfig_",
                "continuousDecodingConfig_",
              };
              java.lang.String info =
                  "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0007" +
                  "";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<ex.grpc.Wenet.Request.DecodeConfig> parser = PARSER;
            if (parser == null) {
              synchronized (ex.grpc.Wenet.Request.DecodeConfig.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<ex.grpc.Wenet.Request.DecodeConfig>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:wenet.Request.DecodeConfig)
      private static final ex.grpc.Wenet.Request.DecodeConfig DEFAULT_INSTANCE;
      static {
        DecodeConfig defaultInstance = new DecodeConfig();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          DecodeConfig.class, defaultInstance);
      }

      public static ex.grpc.Wenet.Request.DecodeConfig getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<DecodeConfig> PARSER;

      public static com.google.protobuf.Parser<DecodeConfig> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int requestPayloadCase_ = 0;
    private java.lang.Object requestPayload_;
    public enum RequestPayloadCase {
      DECODE_CONFIG(1),
      AUDIO_DATA(2),
      REQUESTPAYLOAD_NOT_SET(0);
      private final int value;
      private RequestPayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestPayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static RequestPayloadCase forNumber(int value) {
        switch (value) {
          case 1: return DECODE_CONFIG;
          case 2: return AUDIO_DATA;
          case 0: return REQUESTPAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public RequestPayloadCase
    getRequestPayloadCase() {
      return RequestPayloadCase.forNumber(
          requestPayloadCase_);
    }

    private void clearRequestPayload() {
      requestPayloadCase_ = 0;
      requestPayload_ = null;
    }

    public static final int DECODE_CONFIG_FIELD_NUMBER = 1;
    /**
     * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
     */
    @java.lang.Override
    public boolean hasDecodeConfig() {
      return requestPayloadCase_ == 1;
    }
    /**
     * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
     */
    @java.lang.Override
    public ex.grpc.Wenet.Request.DecodeConfig getDecodeConfig() {
      if (requestPayloadCase_ == 1) {
         return (ex.grpc.Wenet.Request.DecodeConfig) requestPayload_;
      }
      return ex.grpc.Wenet.Request.DecodeConfig.getDefaultInstance();
    }
    /**
     * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
     */
    private void setDecodeConfig(ex.grpc.Wenet.Request.DecodeConfig value) {
      value.getClass();
  requestPayload_ = value;
      requestPayloadCase_ = 1;
    }
    /**
     * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
     */
    private void mergeDecodeConfig(ex.grpc.Wenet.Request.DecodeConfig value) {
      value.getClass();
  if (requestPayloadCase_ == 1 &&
          requestPayload_ != ex.grpc.Wenet.Request.DecodeConfig.getDefaultInstance()) {
        requestPayload_ = ex.grpc.Wenet.Request.DecodeConfig.newBuilder((ex.grpc.Wenet.Request.DecodeConfig) requestPayload_)
            .mergeFrom(value).buildPartial();
      } else {
        requestPayload_ = value;
      }
      requestPayloadCase_ = 1;
    }
    /**
     * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
     */
    private void clearDecodeConfig() {
      if (requestPayloadCase_ == 1) {
        requestPayloadCase_ = 0;
        requestPayload_ = null;
      }
    }

    public static final int AUDIO_DATA_FIELD_NUMBER = 2;
    /**
     * <code>bytes audio_data = 2;</code>
     * @return Whether the audioData field is set.
     */
    @java.lang.Override
    public boolean hasAudioData() {
      return requestPayloadCase_ == 2;
    }
    /**
     * <code>bytes audio_data = 2;</code>
     * @return The audioData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAudioData() {
      if (requestPayloadCase_ == 2) {
        return (com.google.protobuf.ByteString) requestPayload_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes audio_data = 2;</code>
     * @param value The audioData to set.
     */
    private void setAudioData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  requestPayloadCase_ = 2;
      requestPayload_ = value;
    }
    /**
     * <code>bytes audio_data = 2;</code>
     */
    private void clearAudioData() {
      if (requestPayloadCase_ == 2) {
        requestPayloadCase_ = 0;
        requestPayload_ = null;
      }
    }

    public static ex.grpc.Wenet.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ex.grpc.Wenet.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ex.grpc.Wenet.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ex.grpc.Wenet.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ex.grpc.Wenet.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ex.grpc.Wenet.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ex.grpc.Wenet.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ex.grpc.Wenet.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ex.grpc.Wenet.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ex.grpc.Wenet.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ex.grpc.Wenet.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ex.grpc.Wenet.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ex.grpc.Wenet.Request prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code wenet.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ex.grpc.Wenet.Request, Builder> implements
        // @@protoc_insertion_point(builder_implements:wenet.Request)
        ex.grpc.Wenet.RequestOrBuilder {
      // Construct using ex.grpc.Wenet.Request.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public RequestPayloadCase
          getRequestPayloadCase() {
        return instance.getRequestPayloadCase();
      }

      public Builder clearRequestPayload() {
        copyOnWrite();
        instance.clearRequestPayload();
        return this;
      }


      /**
       * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
       */
      @java.lang.Override
      public boolean hasDecodeConfig() {
        return instance.hasDecodeConfig();
      }
      /**
       * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
       */
      @java.lang.Override
      public ex.grpc.Wenet.Request.DecodeConfig getDecodeConfig() {
        return instance.getDecodeConfig();
      }
      /**
       * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
       */
      public Builder setDecodeConfig(ex.grpc.Wenet.Request.DecodeConfig value) {
        copyOnWrite();
        instance.setDecodeConfig(value);
        return this;
      }
      /**
       * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
       */
      public Builder setDecodeConfig(
          ex.grpc.Wenet.Request.DecodeConfig.Builder builderForValue) {
        copyOnWrite();
        instance.setDecodeConfig(builderForValue.build());
        return this;
      }
      /**
       * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
       */
      public Builder mergeDecodeConfig(ex.grpc.Wenet.Request.DecodeConfig value) {
        copyOnWrite();
        instance.mergeDecodeConfig(value);
        return this;
      }
      /**
       * <code>.wenet.Request.DecodeConfig decode_config = 1;</code>
       */
      public Builder clearDecodeConfig() {
        copyOnWrite();
        instance.clearDecodeConfig();
        return this;
      }

      /**
       * <code>bytes audio_data = 2;</code>
       * @return Whether the audioData field is set.
       */
      @java.lang.Override
      public boolean hasAudioData() {
        return instance.hasAudioData();
      }
      /**
       * <code>bytes audio_data = 2;</code>
       * @return The audioData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAudioData() {
        return instance.getAudioData();
      }
      /**
       * <code>bytes audio_data = 2;</code>
       * @param value The audioData to set.
       * @return This builder for chaining.
       */
      public Builder setAudioData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAudioData(value);
        return this;
      }
      /**
       * <code>bytes audio_data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAudioData() {
        copyOnWrite();
        instance.clearAudioData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wenet.Request)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ex.grpc.Wenet.Request();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "requestPayload_",
              "requestPayloadCase_",
              ex.grpc.Wenet.Request.DecodeConfig.class,
            };
            java.lang.String info =
                "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001<\u0000\u0002=" +
                "\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ex.grpc.Wenet.Request> parser = PARSER;
          if (parser == null) {
            synchronized (ex.grpc.Wenet.Request.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ex.grpc.Wenet.Request>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wenet.Request)
    private static final ex.grpc.Wenet.Request DEFAULT_INSTANCE;
    static {
      Request defaultInstance = new Request();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Request.class, defaultInstance);
    }

    public static ex.grpc.Wenet.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Request> PARSER;

    public static com.google.protobuf.Parser<Request> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wenet.Response)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.wenet.Response.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.wenet.Response.Status status = 1;</code>
     * @return The status.
     */
    ex.grpc.Wenet.Response.Status getStatus();

    /**
     * <code>.wenet.Response.Type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.wenet.Response.Type type = 2;</code>
     * @return The type.
     */
    ex.grpc.Wenet.Response.Type getType();

    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    java.util.List<ex.grpc.Wenet.Response.OneBest> 
        getNbestList();
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    ex.grpc.Wenet.Response.OneBest getNbest(int index);
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    int getNbestCount();
  }
  /**
   * Protobuf type {@code wenet.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageLite<
          Response, Response.Builder> implements
      // @@protoc_insertion_point(message_implements:wenet.Response)
      ResponseOrBuilder {
    private Response() {
      nbest_ = emptyProtobufList();
    }
    /**
     * Protobuf enum {@code wenet.Response.Status}
     */
    public enum Status
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>ok = 0;</code>
       */
      ok(0),
      /**
       * <code>failed = 1;</code>
       */
      failed(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ok = 0;</code>
       */
      public static final int ok_VALUE = 0;
      /**
       * <code>failed = 1;</code>
       */
      public static final int failed_VALUE = 1;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return ok;
          case 1: return failed;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              @java.lang.Override
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return StatusVerifier.INSTANCE;
      }

      private static final class StatusVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StatusVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return Status.forNumber(number) != null;
              }
            };

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:wenet.Response.Status)
    }

    /**
     * Protobuf enum {@code wenet.Response.Type}
     */
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>server_ready = 0;</code>
       */
      server_ready(0),
      /**
       * <code>partial_result = 1;</code>
       */
      partial_result(1),
      /**
       * <code>final_result = 2;</code>
       */
      final_result(2),
      /**
       * <code>speech_end = 3;</code>
       */
      speech_end(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>server_ready = 0;</code>
       */
      public static final int server_ready_VALUE = 0;
      /**
       * <code>partial_result = 1;</code>
       */
      public static final int partial_result_VALUE = 1;
      /**
       * <code>final_result = 2;</code>
       */
      public static final int final_result_VALUE = 2;
      /**
       * <code>speech_end = 3;</code>
       */
      public static final int speech_end_VALUE = 3;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return server_ready;
          case 1: return partial_result;
          case 2: return final_result;
          case 3: return speech_end;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              @java.lang.Override
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return TypeVerifier.INSTANCE;
      }

      private static final class TypeVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new TypeVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return Type.forNumber(number) != null;
              }
            };

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:wenet.Response.Type)
    }

    public interface OneBestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:wenet.Response.OneBest)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>string sentence = 1;</code>
       * @return The sentence.
       */
      java.lang.String getSentence();
      /**
       * <code>string sentence = 1;</code>
       * @return The bytes for sentence.
       */
      com.google.protobuf.ByteString
          getSentenceBytes();

      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      java.util.List<ex.grpc.Wenet.Response.OnePiece> 
          getWordpiecesList();
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      ex.grpc.Wenet.Response.OnePiece getWordpieces(int index);
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      int getWordpiecesCount();
    }
    /**
     * Protobuf type {@code wenet.Response.OneBest}
     */
    public  static final class OneBest extends
        com.google.protobuf.GeneratedMessageLite<
            OneBest, OneBest.Builder> implements
        // @@protoc_insertion_point(message_implements:wenet.Response.OneBest)
        OneBestOrBuilder {
      private OneBest() {
        sentence_ = "";
        wordpieces_ = emptyProtobufList();
      }
      public static final int SENTENCE_FIELD_NUMBER = 1;
      private java.lang.String sentence_;
      /**
       * <code>string sentence = 1;</code>
       * @return The sentence.
       */
      @java.lang.Override
      public java.lang.String getSentence() {
        return sentence_;
      }
      /**
       * <code>string sentence = 1;</code>
       * @return The bytes for sentence.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSentenceBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(sentence_);
      }
      /**
       * <code>string sentence = 1;</code>
       * @param value The sentence to set.
       */
      private void setSentence(
          java.lang.String value) {
        java.lang.Class<?> valueClass = value.getClass();
  
        sentence_ = value;
      }
      /**
       * <code>string sentence = 1;</code>
       */
      private void clearSentence() {
        
        sentence_ = getDefaultInstance().getSentence();
      }
      /**
       * <code>string sentence = 1;</code>
       * @param value The bytes for sentence to set.
       */
      private void setSentenceBytes(
          com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        sentence_ = value.toStringUtf8();
        
      }

      public static final int WORDPIECES_FIELD_NUMBER = 2;
      private com.google.protobuf.Internal.ProtobufList<ex.grpc.Wenet.Response.OnePiece> wordpieces_;
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      @java.lang.Override
      public java.util.List<ex.grpc.Wenet.Response.OnePiece> getWordpiecesList() {
        return wordpieces_;
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      public java.util.List<? extends ex.grpc.Wenet.Response.OnePieceOrBuilder> 
          getWordpiecesOrBuilderList() {
        return wordpieces_;
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      @java.lang.Override
      public int getWordpiecesCount() {
        return wordpieces_.size();
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      @java.lang.Override
      public ex.grpc.Wenet.Response.OnePiece getWordpieces(int index) {
        return wordpieces_.get(index);
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      public ex.grpc.Wenet.Response.OnePieceOrBuilder getWordpiecesOrBuilder(
          int index) {
        return wordpieces_.get(index);
      }
      private void ensureWordpiecesIsMutable() {
        com.google.protobuf.Internal.ProtobufList<ex.grpc.Wenet.Response.OnePiece> tmp = wordpieces_;
        if (!tmp.isModifiable()) {
          wordpieces_ =
              com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
         }
      }

      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      private void setWordpieces(
          int index, ex.grpc.Wenet.Response.OnePiece value) {
        value.getClass();
  ensureWordpiecesIsMutable();
        wordpieces_.set(index, value);
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      private void addWordpieces(ex.grpc.Wenet.Response.OnePiece value) {
        value.getClass();
  ensureWordpiecesIsMutable();
        wordpieces_.add(value);
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      private void addWordpieces(
          int index, ex.grpc.Wenet.Response.OnePiece value) {
        value.getClass();
  ensureWordpiecesIsMutable();
        wordpieces_.add(index, value);
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      private void addAllWordpieces(
          java.lang.Iterable<? extends ex.grpc.Wenet.Response.OnePiece> values) {
        ensureWordpiecesIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
            values, wordpieces_);
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      private void clearWordpieces() {
        wordpieces_ = emptyProtobufList();
      }
      /**
       * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
       */
      private void removeWordpieces(int index) {
        ensureWordpiecesIsMutable();
        wordpieces_.remove(index);
      }

      public static ex.grpc.Wenet.Response.OneBest parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OneBest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Response.OneBest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Response.OneBest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(ex.grpc.Wenet.Response.OneBest prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code wenet.Response.OneBest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            ex.grpc.Wenet.Response.OneBest, Builder> implements
          // @@protoc_insertion_point(builder_implements:wenet.Response.OneBest)
          ex.grpc.Wenet.Response.OneBestOrBuilder {
        // Construct using ex.grpc.Wenet.Response.OneBest.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>string sentence = 1;</code>
         * @return The sentence.
         */
        @java.lang.Override
        public java.lang.String getSentence() {
          return instance.getSentence();
        }
        /**
         * <code>string sentence = 1;</code>
         * @return The bytes for sentence.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getSentenceBytes() {
          return instance.getSentenceBytes();
        }
        /**
         * <code>string sentence = 1;</code>
         * @param value The sentence to set.
         * @return This builder for chaining.
         */
        public Builder setSentence(
            java.lang.String value) {
          copyOnWrite();
          instance.setSentence(value);
          return this;
        }
        /**
         * <code>string sentence = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearSentence() {
          copyOnWrite();
          instance.clearSentence();
          return this;
        }
        /**
         * <code>string sentence = 1;</code>
         * @param value The bytes for sentence to set.
         * @return This builder for chaining.
         */
        public Builder setSentenceBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setSentenceBytes(value);
          return this;
        }

        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        @java.lang.Override
        public java.util.List<ex.grpc.Wenet.Response.OnePiece> getWordpiecesList() {
          return java.util.Collections.unmodifiableList(
              instance.getWordpiecesList());
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        @java.lang.Override
        public int getWordpiecesCount() {
          return instance.getWordpiecesCount();
        }/**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        @java.lang.Override
        public ex.grpc.Wenet.Response.OnePiece getWordpieces(int index) {
          return instance.getWordpieces(index);
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder setWordpieces(
            int index, ex.grpc.Wenet.Response.OnePiece value) {
          copyOnWrite();
          instance.setWordpieces(index, value);
          return this;
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder setWordpieces(
            int index, ex.grpc.Wenet.Response.OnePiece.Builder builderForValue) {
          copyOnWrite();
          instance.setWordpieces(index,
              builderForValue.build());
          return this;
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder addWordpieces(ex.grpc.Wenet.Response.OnePiece value) {
          copyOnWrite();
          instance.addWordpieces(value);
          return this;
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder addWordpieces(
            int index, ex.grpc.Wenet.Response.OnePiece value) {
          copyOnWrite();
          instance.addWordpieces(index, value);
          return this;
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder addWordpieces(
            ex.grpc.Wenet.Response.OnePiece.Builder builderForValue) {
          copyOnWrite();
          instance.addWordpieces(builderForValue.build());
          return this;
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder addWordpieces(
            int index, ex.grpc.Wenet.Response.OnePiece.Builder builderForValue) {
          copyOnWrite();
          instance.addWordpieces(index,
              builderForValue.build());
          return this;
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder addAllWordpieces(
            java.lang.Iterable<? extends ex.grpc.Wenet.Response.OnePiece> values) {
          copyOnWrite();
          instance.addAllWordpieces(values);
          return this;
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder clearWordpieces() {
          copyOnWrite();
          instance.clearWordpieces();
          return this;
        }
        /**
         * <code>repeated .wenet.Response.OnePiece wordpieces = 2;</code>
         */
        public Builder removeWordpieces(int index) {
          copyOnWrite();
          instance.removeWordpieces(index);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:wenet.Response.OneBest)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new ex.grpc.Wenet.Response.OneBest();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "sentence_",
                "wordpieces_",
                ex.grpc.Wenet.Response.OnePiece.class,
              };
              java.lang.String info =
                  "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002\u001b" +
                  "";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<ex.grpc.Wenet.Response.OneBest> parser = PARSER;
            if (parser == null) {
              synchronized (ex.grpc.Wenet.Response.OneBest.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<ex.grpc.Wenet.Response.OneBest>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:wenet.Response.OneBest)
      private static final ex.grpc.Wenet.Response.OneBest DEFAULT_INSTANCE;
      static {
        OneBest defaultInstance = new OneBest();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          OneBest.class, defaultInstance);
      }

      public static ex.grpc.Wenet.Response.OneBest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<OneBest> PARSER;

      public static com.google.protobuf.Parser<OneBest> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public interface OnePieceOrBuilder extends
        // @@protoc_insertion_point(interface_extends:wenet.Response.OnePiece)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>string word = 1;</code>
       * @return The word.
       */
      java.lang.String getWord();
      /**
       * <code>string word = 1;</code>
       * @return The bytes for word.
       */
      com.google.protobuf.ByteString
          getWordBytes();

      /**
       * <code>int32 start = 2;</code>
       * @return The start.
       */
      int getStart();

      /**
       * <code>int32 end = 3;</code>
       * @return The end.
       */
      int getEnd();
    }
    /**
     * Protobuf type {@code wenet.Response.OnePiece}
     */
    public  static final class OnePiece extends
        com.google.protobuf.GeneratedMessageLite<
            OnePiece, OnePiece.Builder> implements
        // @@protoc_insertion_point(message_implements:wenet.Response.OnePiece)
        OnePieceOrBuilder {
      private OnePiece() {
        word_ = "";
      }
      public static final int WORD_FIELD_NUMBER = 1;
      private java.lang.String word_;
      /**
       * <code>string word = 1;</code>
       * @return The word.
       */
      @java.lang.Override
      public java.lang.String getWord() {
        return word_;
      }
      /**
       * <code>string word = 1;</code>
       * @return The bytes for word.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getWordBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(word_);
      }
      /**
       * <code>string word = 1;</code>
       * @param value The word to set.
       */
      private void setWord(
          java.lang.String value) {
        java.lang.Class<?> valueClass = value.getClass();
  
        word_ = value;
      }
      /**
       * <code>string word = 1;</code>
       */
      private void clearWord() {
        
        word_ = getDefaultInstance().getWord();
      }
      /**
       * <code>string word = 1;</code>
       * @param value The bytes for word to set.
       */
      private void setWordBytes(
          com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        word_ = value.toStringUtf8();
        
      }

      public static final int START_FIELD_NUMBER = 2;
      private int start_;
      /**
       * <code>int32 start = 2;</code>
       * @return The start.
       */
      @java.lang.Override
      public int getStart() {
        return start_;
      }
      /**
       * <code>int32 start = 2;</code>
       * @param value The start to set.
       */
      private void setStart(int value) {
        
        start_ = value;
      }
      /**
       * <code>int32 start = 2;</code>
       */
      private void clearStart() {
        
        start_ = 0;
      }

      public static final int END_FIELD_NUMBER = 3;
      private int end_;
      /**
       * <code>int32 end = 3;</code>
       * @return The end.
       */
      @java.lang.Override
      public int getEnd() {
        return end_;
      }
      /**
       * <code>int32 end = 3;</code>
       * @param value The end to set.
       */
      private void setEnd(int value) {
        
        end_ = value;
      }
      /**
       * <code>int32 end = 3;</code>
       */
      private void clearEnd() {
        
        end_ = 0;
      }

      public static ex.grpc.Wenet.Response.OnePiece parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static ex.grpc.Wenet.Response.OnePiece parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(ex.grpc.Wenet.Response.OnePiece prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code wenet.Response.OnePiece}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            ex.grpc.Wenet.Response.OnePiece, Builder> implements
          // @@protoc_insertion_point(builder_implements:wenet.Response.OnePiece)
          ex.grpc.Wenet.Response.OnePieceOrBuilder {
        // Construct using ex.grpc.Wenet.Response.OnePiece.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>string word = 1;</code>
         * @return The word.
         */
        @java.lang.Override
        public java.lang.String getWord() {
          return instance.getWord();
        }
        /**
         * <code>string word = 1;</code>
         * @return The bytes for word.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getWordBytes() {
          return instance.getWordBytes();
        }
        /**
         * <code>string word = 1;</code>
         * @param value The word to set.
         * @return This builder for chaining.
         */
        public Builder setWord(
            java.lang.String value) {
          copyOnWrite();
          instance.setWord(value);
          return this;
        }
        /**
         * <code>string word = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearWord() {
          copyOnWrite();
          instance.clearWord();
          return this;
        }
        /**
         * <code>string word = 1;</code>
         * @param value The bytes for word to set.
         * @return This builder for chaining.
         */
        public Builder setWordBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setWordBytes(value);
          return this;
        }

        /**
         * <code>int32 start = 2;</code>
         * @return The start.
         */
        @java.lang.Override
        public int getStart() {
          return instance.getStart();
        }
        /**
         * <code>int32 start = 2;</code>
         * @param value The start to set.
         * @return This builder for chaining.
         */
        public Builder setStart(int value) {
          copyOnWrite();
          instance.setStart(value);
          return this;
        }
        /**
         * <code>int32 start = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearStart() {
          copyOnWrite();
          instance.clearStart();
          return this;
        }

        /**
         * <code>int32 end = 3;</code>
         * @return The end.
         */
        @java.lang.Override
        public int getEnd() {
          return instance.getEnd();
        }
        /**
         * <code>int32 end = 3;</code>
         * @param value The end to set.
         * @return This builder for chaining.
         */
        public Builder setEnd(int value) {
          copyOnWrite();
          instance.setEnd(value);
          return this;
        }
        /**
         * <code>int32 end = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearEnd() {
          copyOnWrite();
          instance.clearEnd();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:wenet.Response.OnePiece)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new ex.grpc.Wenet.Response.OnePiece();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "word_",
                "start_",
                "end_",
              };
              java.lang.String info =
                  "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
                  "\u0003\u0004";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<ex.grpc.Wenet.Response.OnePiece> parser = PARSER;
            if (parser == null) {
              synchronized (ex.grpc.Wenet.Response.OnePiece.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<ex.grpc.Wenet.Response.OnePiece>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:wenet.Response.OnePiece)
      private static final ex.grpc.Wenet.Response.OnePiece DEFAULT_INSTANCE;
      static {
        OnePiece defaultInstance = new OnePiece();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          OnePiece.class, defaultInstance);
      }

      public static ex.grpc.Wenet.Response.OnePiece getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<OnePiece> PARSER;

      public static com.google.protobuf.Parser<OnePiece> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.wenet.Response.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.wenet.Response.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public ex.grpc.Wenet.Response.Status getStatus() {
      ex.grpc.Wenet.Response.Status result = ex.grpc.Wenet.Response.Status.forNumber(status_);
      return result == null ? ex.grpc.Wenet.Response.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.wenet.Response.Status status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.wenet.Response.Status status = 1;</code>
     * @param value The status to set.
     */
    private void setStatus(ex.grpc.Wenet.Response.Status value) {
      status_ = value.getNumber();
      
    }
    /**
     * <code>.wenet.Response.Status status = 1;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.wenet.Response.Type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.wenet.Response.Type type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public ex.grpc.Wenet.Response.Type getType() {
      ex.grpc.Wenet.Response.Type result = ex.grpc.Wenet.Response.Type.forNumber(type_);
      return result == null ? ex.grpc.Wenet.Response.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.wenet.Response.Type type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>.wenet.Response.Type type = 2;</code>
     * @param value The type to set.
     */
    private void setType(ex.grpc.Wenet.Response.Type value) {
      type_ = value.getNumber();
      
    }
    /**
     * <code>.wenet.Response.Type type = 2;</code>
     */
    private void clearType() {
      
      type_ = 0;
    }

    public static final int NBEST_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<ex.grpc.Wenet.Response.OneBest> nbest_;
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    @java.lang.Override
    public java.util.List<ex.grpc.Wenet.Response.OneBest> getNbestList() {
      return nbest_;
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    public java.util.List<? extends ex.grpc.Wenet.Response.OneBestOrBuilder> 
        getNbestOrBuilderList() {
      return nbest_;
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    @java.lang.Override
    public int getNbestCount() {
      return nbest_.size();
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    @java.lang.Override
    public ex.grpc.Wenet.Response.OneBest getNbest(int index) {
      return nbest_.get(index);
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    public ex.grpc.Wenet.Response.OneBestOrBuilder getNbestOrBuilder(
        int index) {
      return nbest_.get(index);
    }
    private void ensureNbestIsMutable() {
      com.google.protobuf.Internal.ProtobufList<ex.grpc.Wenet.Response.OneBest> tmp = nbest_;
      if (!tmp.isModifiable()) {
        nbest_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    private void setNbest(
        int index, ex.grpc.Wenet.Response.OneBest value) {
      value.getClass();
  ensureNbestIsMutable();
      nbest_.set(index, value);
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    private void addNbest(ex.grpc.Wenet.Response.OneBest value) {
      value.getClass();
  ensureNbestIsMutable();
      nbest_.add(value);
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    private void addNbest(
        int index, ex.grpc.Wenet.Response.OneBest value) {
      value.getClass();
  ensureNbestIsMutable();
      nbest_.add(index, value);
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    private void addAllNbest(
        java.lang.Iterable<? extends ex.grpc.Wenet.Response.OneBest> values) {
      ensureNbestIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, nbest_);
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    private void clearNbest() {
      nbest_ = emptyProtobufList();
    }
    /**
     * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
     */
    private void removeNbest(int index) {
      ensureNbestIsMutable();
      nbest_.remove(index);
    }

    public static ex.grpc.Wenet.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ex.grpc.Wenet.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ex.grpc.Wenet.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ex.grpc.Wenet.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ex.grpc.Wenet.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ex.grpc.Wenet.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ex.grpc.Wenet.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ex.grpc.Wenet.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ex.grpc.Wenet.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ex.grpc.Wenet.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ex.grpc.Wenet.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ex.grpc.Wenet.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ex.grpc.Wenet.Response prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code wenet.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ex.grpc.Wenet.Response, Builder> implements
        // @@protoc_insertion_point(builder_implements:wenet.Response)
        ex.grpc.Wenet.ResponseOrBuilder {
      // Construct using ex.grpc.Wenet.Response.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.wenet.Response.Status status = 1;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.wenet.Response.Status status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.wenet.Response.Status status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public ex.grpc.Wenet.Response.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.wenet.Response.Status status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(ex.grpc.Wenet.Response.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.wenet.Response.Status status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>.wenet.Response.Type type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>.wenet.Response.Type type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>.wenet.Response.Type type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public ex.grpc.Wenet.Response.Type getType() {
        return instance.getType();
      }
      /**
       * <code>.wenet.Response.Type type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(ex.grpc.Wenet.Response.Type value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>.wenet.Response.Type type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      @java.lang.Override
      public java.util.List<ex.grpc.Wenet.Response.OneBest> getNbestList() {
        return java.util.Collections.unmodifiableList(
            instance.getNbestList());
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      @java.lang.Override
      public int getNbestCount() {
        return instance.getNbestCount();
      }/**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      @java.lang.Override
      public ex.grpc.Wenet.Response.OneBest getNbest(int index) {
        return instance.getNbest(index);
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder setNbest(
          int index, ex.grpc.Wenet.Response.OneBest value) {
        copyOnWrite();
        instance.setNbest(index, value);
        return this;
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder setNbest(
          int index, ex.grpc.Wenet.Response.OneBest.Builder builderForValue) {
        copyOnWrite();
        instance.setNbest(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder addNbest(ex.grpc.Wenet.Response.OneBest value) {
        copyOnWrite();
        instance.addNbest(value);
        return this;
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder addNbest(
          int index, ex.grpc.Wenet.Response.OneBest value) {
        copyOnWrite();
        instance.addNbest(index, value);
        return this;
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder addNbest(
          ex.grpc.Wenet.Response.OneBest.Builder builderForValue) {
        copyOnWrite();
        instance.addNbest(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder addNbest(
          int index, ex.grpc.Wenet.Response.OneBest.Builder builderForValue) {
        copyOnWrite();
        instance.addNbest(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder addAllNbest(
          java.lang.Iterable<? extends ex.grpc.Wenet.Response.OneBest> values) {
        copyOnWrite();
        instance.addAllNbest(values);
        return this;
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder clearNbest() {
        copyOnWrite();
        instance.clearNbest();
        return this;
      }
      /**
       * <code>repeated .wenet.Response.OneBest nbest = 3;</code>
       */
      public Builder removeNbest(int index) {
        copyOnWrite();
        instance.removeNbest(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wenet.Response)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ex.grpc.Wenet.Response();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "status_",
              "type_",
              "nbest_",
              ex.grpc.Wenet.Response.OneBest.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\f\u0002\f\u0003" +
                "\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ex.grpc.Wenet.Response> parser = PARSER;
          if (parser == null) {
            synchronized (ex.grpc.Wenet.Response.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ex.grpc.Wenet.Response>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wenet.Response)
    private static final ex.grpc.Wenet.Response DEFAULT_INSTANCE;
    static {
      Response defaultInstance = new Response();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Response.class, defaultInstance);
    }

    public static ex.grpc.Wenet.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Response> PARSER;

    public static com.google.protobuf.Parser<Response> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
